name: fashion_shoping
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # For animation
  animations: ^2.0.11

  # For Showing loading
  shimmer: ^3.0.0

  # For UI
  carousel_slider_plus: ^7.1.0
  smooth_page_indicator: ^1.2.1
  getwidget: ^6.0.0
  bottom_navy_bar: ^6.1.0

  # Storage for simple data
  shared_preferences: ^2.5.2

  # For State Management
  get_cli: ^1.9.1
  get: ^4.7.2

  # For Drop Down
  dropdown_search: ^6.0.2

  # For customizable rating bar
  flutter_rating_bar: ^4.0.1

  # For Image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # For format numbers, dates, currencies, messages
  intl: ^0.19.0

dev_dependencies:
  flutter_native_splash: "^2.4.3"
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Moved here

flutter_native_splash:
  color: "#DB3022"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700