// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByt32k6EirgZHIgaFH36vRmglIOL_LlV0',
    appId: '1:278184573009:web:ddfde7c4c4dfe7c67ca070',
    messagingSenderId: '278184573009',
    projectId: 'fasion-shopping',
    authDomain: 'fasion-shopping.firebaseapp.com',
    storageBucket: 'fasion-shopping.firebasestorage.app',
    measurementId: 'G-ET7XGYCF79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmMSApX0_b3BkN2CX74Pi60ymMhlecPdM',
    appId: '1:278184573009:android:72d36f5a5251797b7ca070',
    messagingSenderId: '278184573009',
    projectId: 'fasion-shopping',
    storageBucket: 'fasion-shopping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5VXyHKH6Sef_LBwuFhj19g0Rvnik_k5M',
    appId: '1:278184573009:ios:7aa3053eb8b0299c7ca070',
    messagingSenderId: '278184573009',
    projectId: 'fasion-shopping',
    storageBucket: 'fasion-shopping.firebasestorage.app',
    iosBundleId: 'com.example.fashionShoping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5VXyHKH6Sef_LBwuFhj19g0Rvnik_k5M',
    appId: '1:278184573009:ios:7aa3053eb8b0299c7ca070',
    messagingSenderId: '278184573009',
    projectId: 'fasion-shopping',
    storageBucket: 'fasion-shopping.firebasestorage.app',
    iosBundleId: 'com.example.fashionShoping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByt32k6EirgZHIgaFH36vRmglIOL_LlV0',
    appId: '1:278184573009:web:9c5e557399e939827ca070',
    messagingSenderId: '278184573009',
    projectId: 'fasion-shopping',
    authDomain: 'fasion-shopping.firebaseapp.com',
    storageBucket: 'fasion-shopping.firebasestorage.app',
    measurementId: 'G-YFFDLM5SCF',
  );
}
